### PR TITLE
Add IntentState table

### PR DESCRIPTION
**Pull request by Narrev**
I really have no idea whether this is what is supposed to be the solution, but it will probably save you from some errors.

### CODE REVIEW

**Comment by Narrev** [comment]
Actually, I think this does get inserted into via getfenv()

**Comment by eLunate** [comment]
What was this supoosed to fix?

**Comment by eLunate** [comment]
No, no, you're right. I'd neglected to add an `IntentState` table despite using it a couple of times within the code.

**Comment by Narrev** [comment]
Oh, okay good

**Pull request closed without merging**
