### PR TITLE
Decal --> Image

### PR DESCRIPTION
**Pull request by Narrev**

### CODE REVIEW

**Comment by Gskartwii** [comment]
I've fixed the pull request handler on the CI and I must comment here to run it. It should then set a status on your commit with the build log.

**Comment by Gskartwii** [comment]
No, assigning people did the trick.

**Comment by Narrev** [comment]
Soooooo.... now what?

**Comment by eLunate** [comment]
Oh well you see I was supposed to merge it but I can't on mobile and I forgot when I wasn't on mobile.

**Comment by Narrev** [comment]
Alright. On mobile, you can switch to Desktop version at the very bottom right of the page.

**Comment by Validark** [comment]
I remembered this today. It made me laugh. I mean, who would find such a thing?

**Pull request merged**
